name: Deploy Heroku

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "view/**"
      - "package.json"
      - "Procfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "poohstest"
          heroku_email: "kurikokudo@gmail.com"

